Re-enabled xpub functionality.
Bitcoin-com/bitcoin-cash-merchant-ios pull request #27
Opened 2022-07-07 14:53 UTC by echoelman

- Reverted commit 5e8cbe832677c992dbe6c75f443b51fa7450a607
- WalletManager's reliance on HDWallet was replaced with a modified version of ReadOnlyHDWallet. This class was derived from Horizontal Systems' HdWalletKit (https://github.com/horizontalsystems/hd-wallet-kit-ios/blob/master/HdWalletKit/Classes/ReadOnlyHDWallet.swift)
- ReadOnlyHDWallet derives additional public keys based on the merchant's original xpub key, whereas the original HDWallet implementation created a new private key and keychain to handle key derivation.
- xpub indexing is handled exclusively by UserManager

2022-07-21 01:40 UTC, jenbitcoin requested changes
@echoelman based on the changes, i expected to be able to input xupbkey instead of a bch address.. but i can't seem to add an xpubkey in our destination address.. @pokkst can you confirm if I understood that correctly?

![Simulator Screen Shot - iPhone 13 Pro - 2022-07-21 at 09 38 51](https://user-images.githubusercontent.com/52556996/180111078-1d369581-0495-4d26-835f-59dfc08fc265.png)

2022-07-21 06:42 UTC, jenbitcoin commented
I think there are some missing pieces here.. if you check `validateAndStoreAddress(address: String)` it created paymenTarget of type .address inside the function, so it will never reach `if paymentTarget.type == .xPub`

that function should accept a paymenTarget, instead. Set the address / xpub as target, and temporarily set type to .invalid.. This `setup()` should be able to change the type to correct type


![Screen Shot 2022-07-21 at 2 41 09 PM](https://user-images.githubusercontent.com/52556996/180146633-d2a4f80f-7ada-4131-ac54-32be060109f7.png)


Lastly, pls also check `Scan` should work when scanning xpub and address

2022-07-21 16:16 UTC, echoelman commented
Thanks for letting me know about these issues! I will take look at them today.

2022-07-21 18:33 UTC, echoelman commented
I have pushed a new commit with the requested changes after testing them on a physical iOS device. I was also able to scan in an xpub address with the new changes. Please let me know if you have any questions or concerns about this commit.

2022-07-21 22:41 UTC, jenbitcoin commented
i will check when i start work today. thanks for your hardwork

2022-07-22 00:52 UTC, jenbitcoin approved these changes
@echoelman  Will approve PR. But I have one last tiny comment, can you pls fix this part, the title is clipped, and you can merge after :) 
![Simulator Screen Shot - iPhone 13 Pro - 2022-07-22 at 08 48 32](https://user-images.githubusercontent.com/52556996/180338727-6587c3fc-4302-4a97-9da3-8ea9d5640900.png)

2022-07-26 15:00 UTC, echoelman commented
Thanks for letting me know about the view being clipped. Here a screenshot from an iPhone 6s with the requested change:
![IMG_3DA23A16644E-1](https://user-images.githubusercontent.com/26911211/181039341-25b49c96-5a4e-4436-8274-2b20f567bb21.jpeg)


There's quite a bit of extra space now when using the app on an iPad mini: 
<img width="734" alt="Screen Shot 2022-07-26 at 10 48 30 AM" src="https://user-images.githubusercontent.com/26911211/181039232-53f54211-f8e4-48c7-bece-a6737970157e.png">


Probably not a big deal, but let me know if we should polish this up in a way that supports Tablet and Phone formats.

Thanks again!

2022-07-27 08:17 UTC, jenbitcoin commented
@echoelman  yes pls polish the UI so that there's no extra space. thanks!

2022-07-27 15:52 UTC, echoelman commented
Screenshots of the latest commit:

iPad Mini:
![Simulator Screen Shot - iPad mini (5th generation) - 2022-07-27 at 11 50 02](https://user-images.githubusercontent.com/26911211/181292477-8d6281e8-448e-4ecf-8deb-a10bb01e5319.png)

iPhone 6s:
![IMG_0D4D6F857CD6-1](https://user-images.githubusercontent.com/26911211/181292558-e78bb012-e01c-48c0-be9d-7cf532a0fa12.jpeg)

2022-07-31 23:55 UTC, bitcoinstore commented
I'm still super eager to have this ready so it can be promoted.  When paired with an xpub from a cash fusion wallet, this gives merchants privacy in the same ball park as Monero.

2022-08-01 08:36 UTC, jenbitcoin commented
@echoelman thanks for fixing the UI. let's merge!

2022-08-02 11:00 UTC, jenbitcoin commented
if this is still not merged tomorrow, I'll just merge it and create a build

2022-08-03 01:08 UTC, merged